version: '3'

services:
  etcd:
    image: bitnami/etcd:3.4.4
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
      - "2380:2380"

  server:
    build: server/
    depends_on:
      - etcd
    ports:
      - "80:80"
#    environment:
#      - "ETCD_HOST": etcd
#      - "ETCD_PORT": port
