version: '3'

volumes:
  rabbitmq-data:

services:
  etcd:
    image: bitnami/etcd:3.4.4
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine
    hostname: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      #- "5671:5671"
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=galileo
      - RABBITMQ_DEFAULT_PASS=abc123
    restart: unless-stopped

  server:
    build: server/
    depends_on:
      - etcd
      - rabbitmq
    ports:
      - "80:80"
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=calculation
      - RABBITMQ_USER=galileo
      - RABBITMQ_PASS=abc123
    restart: unless-stopped

  client:
    build: client/
    depends_on:
      - etcd
      - rabbitmq
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=calculation
      - RABBITMQ_USER=galileo
      - RABBITMQ_PASS=abc123
    restart: unless-stopped
